headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/ashvantanand/Dev/forge/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
DATA_DIR = "/tmp/forge-data"
DATABASE_URL = "file:/tmp/forge-data/forge.db"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]