import { db, schema } from "@/lib/db";
import { eq } from "drizzle-orm";
import { DEMO_PROJECT_ID } from "./constants";
import demoSeed from "./demo-seed.json";

/**
 * Seed-on-read for the demo project.
 *
 * Production runs on Vercel serverless functions with an ephemeral, per-
 * instance /tmp filesystem (and no Turso configured yet). A demo project
 * created by one request is therefore invisible to the next request, which
 * lands on a different instance — producing "project not found".
 *
 * Rather than depending on runtime writes surviving, we bundle a
 * deterministic, read-only snapshot (demo-seed.json, generated by
 * scripts/build-demo-seed.mjs) and lazily insert it into whatever DB the
 * current instance has. This makes the demo work identically on every
 * instance with zero external services. Real multi-user projects still use
 * the normal write path (and Turso/Blob once configured).
 *
 * Idempotent and concurrency-safe via onConflictDoNothing on primary keys.
 */

interface SeedRow {
  [key: string]: unknown;
}

const DEMO_CONVERSATION_ID = `${DEMO_PROJECT_ID}-conv`;

let seededThisInstance = false;

export function isDemoProjectId(id: string): boolean {
  return id === DEMO_PROJECT_ID;
}

export async function ensureDemoSeeded(id: string): Promise<void> {
  if (id !== DEMO_PROJECT_ID) return;
  // Fast path: once this warm instance has seeded, skip the DB round trip.
  if (seededThisInstance) return;

  // Completeness sentinel: the conversation is inserted LAST, so its presence
  // means every prior insert (project, files, chunks, resources) also ran.
  // Gating on this (rather than just the project row) prevents a partial seed
  // from a mid-way failure being treated as complete forever.
  const complete = await db
    .select({ id: schema.conversations.id })
    .from(schema.conversations)
    .where(eq(schema.conversations.id, DEMO_CONVERSATION_ID))
    .get();

  if (complete) {
    seededThisInstance = true;
    return;
  }

  try {
    const p = demoSeed.project as SeedRow;
    await db
      .insert(schema.projects)
      .values({
        id: DEMO_PROJECT_ID,
        name: p.name as string,
        source: "demo",
        status: "ready",
        summary: (p.summary as string) ?? null,
        metadata: (p.metadata as string) ?? null,
        indexProgress: (p.index_progress as string) ?? null,
        createdAt: (p.created_at as number) ?? Date.now(),
        updatedAt: Date.now(),
      })
      .onConflictDoNothing()
      .run();

    for (const f of demoSeed.files as SeedRow[]) {
      await db
        .insert(schema.files)
        .values({
          id: f.id as string,
          projectId: DEMO_PROJECT_ID,
          path: f.path as string,
          language: (f.language as string) ?? null,
          size: (f.size as number) ?? 0,
          content: (f.content as string) ?? null,
        })
        .onConflictDoNothing()
        .run();
    }

    for (const c of demoSeed.chunks as SeedRow[]) {
      await db
        .insert(schema.chunks)
        .values({
          id: c.id as string,
          projectId: DEMO_PROJECT_ID,
          filePath: c.file_path as string,
          startLine: (c.start_line as number) ?? 1,
          endLine: (c.end_line as number) ?? 1,
          content: c.content as string,
          embedding: (c.embedding as string) ?? null,
          sourceType: (c.source_type as string) ?? "code",
        })
        .onConflictDoNothing()
        .run();
    }

    for (const r of demoSeed.resources as SeedRow[]) {
      await db
        .insert(schema.resources)
        .values({
          id: r.id as string,
          projectId: DEMO_PROJECT_ID,
          type: r.type as string,
          name: r.name as string,
          status: "ready",
          size: (r.size as number) ?? 0,
          storagePath: (r.storage_path as string) ?? null,
          summary: (r.summary as string) ?? null,
          externalUrl: (r.external_url as string) ?? null,
          externalProvider: (r.external_provider as string) ?? null,
          metadata: (r.metadata as string) ?? null,
          createdAt: (r.created_at as number) ?? Date.now(),
        })
        .onConflictDoNothing()
        .run();
    }

    // A starter conversation so the workspace always has one to open.
    const now = Date.now();
    await db
      .insert(schema.conversations)
      .values({
        id: DEMO_CONVERSATION_ID,
        projectId: DEMO_PROJECT_ID,
        title: "Demo walkthrough",
        createdAt: now,
        updatedAt: now,
      })
      .onConflictDoNothing()
      .run();

    seededThisInstance = true;
  } catch (err) {
    // Non-fatal: if a parallel request seeded first, the endpoint will still
    // find the rows. Don't cache success so a partial failure can retry.
    console.error("Demo seed insert failed (will retry on next read):", err);
  }
}
